### ISSUE TITLE
Can a sparse search return weighted values?

### ISSUE THREAD

**Issue by josephroffey** [tidwall/tile38#103]
Hi there,

I'm trying to create a [heatmap](https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap) of currently active points, and to do this I was going to do a sparse search within the bounds of the heat map...

Google's api accepts 'weights' for various locations... Now because the [Documentation](http://tile38.com/commands/intersects/) says that Tile38 'will distribute the results of a search evenly across the requested area' I presume that this would generate an approximate heatmap with points that all had the same weight?

I was wondering, if it was possible to better represent edge values by returning a weighted distribution instead...? E.g. if there were 100 points in one location and 50 in another, an 'even' distribution of two points I would guess might plot two points that were between these 2 locations, but a 'weighted' distribution might plot these 2 points with one having double the weight of the other...

Do you know if my use case makes sense/whether this might be possible to do with some form of search?

**Comment by tidwall** [comment]
Hi Joseph,

I think I understand but correct me if I'm off base.

The SPARSE keyword will not work for your use case. It's intended to split a bounding area into smaller cells, taking the first object that intersects each square.  For example, `SPARSE 2` will split the original search into a grid of 16 smaller cells. Tile38 then returns the first object it finds in each cell:

![untitled-1](https://cloud.githubusercontent.com/assets/1156077/21363180/c3914be4-c6a8-11e6-8bdb-d9b5572d0324.png)

This operation is super fast for huge datasets because it avoids scanning points past the first one it finds per cell.

Perhaps what you are looking for is something that does the inverse, such as scanning a dense set of points and clustering them. These clustered points would then have a weight or some value that is higher if more points are neighboring it. Graphics such as isolines or heatmaps could be created from this data. 

I'm not aware of a way to do this with Tile38 right now, but I'm up for suggestions on syntax or an algorithm.

**Comment by tidwall** [comment]
I'm closing this issue for now. If you have any further question around this topic then feel free to reopen it. Thanks again!

**Comment by danghung-dev** [comment]
@tidwall Do you have any suggestions or an algorithm for building a heatmap? 
Thanks.
