### ISSUE TITLE
Protobuf support wanted

### ISSUE THREAD

**Issue by icewukong** [tidwall/tile38#106]
When we execute spatial queries, the geojson data returned by the server may be large.
If geojson data can be compressed using Pb, will be able to reduce response time,in the case of high concurrency.

**Comment by tidwall** [comment]
Thanks for the suggestion. Are you referring to something this https://github.com/mapbox/geobuf?

**Comment by icewukong** [comment]
Yes, that's what I mean.

**Comment by m1ome** [comment]
@tidwall researching it right now. Trying to implement PoC compatible with geobuf.

**Comment by tidwall** [comment]
@m1ome This one could be a big win.

If the PoC works out what do you think about just having a new [output format](http://tile38.com/commands/intersects/#output-formats) to GET/SET and the search commands, perhaps named GEOBUF(S) or GBOBJECT(S).

**Comment by m1ome** [comment]
@tidwall i am currently looking up into protobuf, never worked with it. If we have PoC I think have a GEOBUF format can be pretty easy.

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for many months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please feel free to reopen if needed.

Thank you!
