### ISSUE TITLE
Support for webhooks into Redis?

### ISSUE THREAD

**Issue by phulst** [tidwall/tile38#108]
First of all, great project. Also thanks for the efforts you've put into the documentation, makes it just so much easier to get my feet wet with this... I'm excited to start playing around with Tile38. 

The webhooks feature is particularly interesting to me, but I have a couple of questions about this: 
- Is there any chance that a Redis integration might be coming for this? I imagine this could work very similar to your current Disque integration, and simply push a small object to a queue when the event gets triggered. (I'd contribute this integration myself but unfortunately don't know Go.) 
- What is a realistic limit for the number of hooks that can be registered concurrently? If I needed to track hundreds or even thousands of objects, and receive a notification when any of these enter/leave a number of geofences, could that be done with hooks, or would that push the limits of what's possible at the moment? 
thanks

**Comment by tidwall** [comment]
Thanks for the kind words and you interest in Tile38.

> Is there any chance that a Redis integration might be coming for this?

I don't currently have Redis integration on the roadmap, but it's certainly possible. There's an [controller/endpoint](https://github.com/tidwall/tile38/tree/master/controller/endpoint) package that provides and interface for adding hook protocols. I suspect that Redis would work very similar to Disque.

> What is a realistic limit for the number of hooks that can be registered concurrently? If I needed to track hundreds or even thousands of objects...

There's no hardcoded limits on the number of hooks though it depends mostly on server and network hardware. It can also depend on the complexity of the object types. The most common hooks simply detect when points enter and exit polygons. In this case Tile38 should have no problem handling many thousands of notifications per second with modest hardware. 

The gRPC hooks are pretty fast and have very low overhead. Disque is very similar in performance (Redis would likely be comparable). HTTP is less predictable in terms of performance because much depends on the endpoint (such as HTTP version, proxies, ssl). 

I hope this information is helpful and let me know if you have any further questions.

**Comment by phulst** [comment]
ok, thanks. well, it looks like Golang has a pretty reasonable learning curve. I may take a stab at this myself and submit a pull request at some point...

**Comment by tidwall** [comment]
That would be fantastic! Let me know if you need a second set of eyes.

**Comment by m1ome** [comment]
@tidwall i will do this FR if you don't mind, looks like @phulst have some issue with this one, IMO redis integration can be pretty usable.

**Comment by tidwall** [comment]
@m1ome Sounds good. Let me know if you have any questions along the way.

**Comment by m1ome** [comment]
@phulst PR on review now, it send all stuff into Redis PubSub queue.

**Comment by m1ome** [comment]
@tidwall i can also create a PR on docs, to document this feature.

**Comment by tidwall** [comment]
@m1ome That would be very helpful. 👍

**Comment by m1ome** [comment]
@tidwall i am on it today.

**Comment by m1ome** [comment]
@tidwall https://github.com/tile38/tile38.github.io/pull/1

**Comment by m1ome** [comment]
@tidwall you can close it i think.
