### ISSUE TITLE
NEARBY sort results by distance

### ISSUE THREAD

**Issue by joernroeder** [tidwall/tile38#130]
Hey, I'm currently playing arround with tile38 and i found #79 and #119 which are both looking very interessting to me while i'm trying to find a point, which sits within the radius of n given points. At the moment i'm using n queries – one for each input point – and i'd like to return the closest point which was found in all subqueries.
During the iteration through the result lists, comparing ids and measuring distance to find the closest point i was wondering wheather i can get back ordered points (by distance) from a query instead of doing it manually afterwards.

Besides from combining multiple queries sorting by distance could be useful in other scenarios as well. What do you think?

**Comment by tidwall** [comment]
Hi Jörn,

Yes, I think this is a very good idea. Having nearby searches ordered by nearest distance is a feature that I have on the roadmap. It's been requested multiple times and is a high priority.

The basic idea is that you should be able to do something like:
```
NEARBY people LIMIT 100 POINT 33 -115 5000
```

Which would return back the 100 nearest objects to that are all within a 5km radius of coordinates 33,-115.

**Comment by joernroeder** [comment]
hey @tidwall,
thanks for looking into this! At the moment it feels like a waste of ressouces to use a pretty high LIMIT just to throw most of the items away after sorting them.
Your example returns up to 100 objects (within the radius) but i also noticed that sometimes it's more helpful to exactly find the n closest points aka https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm for a given point without a given search radius or boundary.
I'm currently doing this by incrementally increasing the search radius until i collected all n neighbors i'm looking for.  
Do you have any plans to add KNN as well?

**Comment by tidwall** [comment]
Yes. We moved away from quadtree/rtree hybrid index to pure rtree for the purpose of supporting k-nn queries. If LIMIT is specified, but the radius is not then the operation will work as you described. At least that is the plan for a future release.

**Comment by tidwall** [comment]
Yes. We moved away from quadtree/rtree hybrid index to pure rtree for the purpose of supporting k-nn & 3D queries. If LIMIT is specified but the radius is not, then the operation will work as you described. At least that is the plan for a future release.

**Comment by joernroeder** [comment]
Wow! Sounds perfect! :)

**Comment by tidwall** [comment]
Glad to hear your enthusiasm and thanks for your interest in Tile38!

**Comment by tomquas** [comment]
exactly my use case. with this feature implemented i will be able to replace my home-grown, redis-based solution entirely with tile38. way to go!

**Comment by tidwall** [comment]
@tomquas That's good to hear. This feature is on the short term roadmap.

**Comment by m1ome** [comment]
I am currently on it, but after PoC we need to test it up for a speed reasons.

**Comment by tidwall** [comment]
@m1ome Sweet. I just added an official issue at #136, I think it matches the describes the feature as discussed.

**Comment by m1ome** [comment]
@tidwall I will write down some benchmark around this to test up new performance on KNN search

**Comment by tidwall** [comment]
@m1ome sounds good. Fwiw, on my system I'm seeing about a 2ms response when doing a kNN search of 10 items on a collection of 10mil points. It should be much quicker, but it's a start.

**Comment by tomquas** [comment]
@tidwall i set up a database with ~23k world cities (source: geonames.org), and stored each one 10 times to get some volume.

`127.0.0.1:9851> scan cities count
{"ok":true,"count":230905,"cursor":0,"elapsed":"11.609µs"}`

this surprised me, though:
`127.0.0.1:9851> nearby cities count point 48.13743 11.57549 20000
{"ok":true,"count":169,"cursor":0,"elapsed":"193.373µs"}
127.0.0.1:9851> nearby cities limit 100 count point 48.13743 11.57549 20000
{"ok":true,"count":169,"cursor":0,"elapsed":"161.027µs"}`

i'd expect the second command incl. the limit clause to return a count of 100 instead of 169.

**Comment by tidwall** [comment]
Based on your example, it looks like when COUNT is specified LIMIT is ignored. This might be a bug with Tile38.

The knn search need to *not* include the meters param, for example:

```
nearby cities limit 100 point 48.13743 11.57549
```

This should return back 100 closest objects.

**Comment by tomquas** [comment]
oh yeah, sorry, that was me not thinking clearly...

`127.0.0.1:9851> nearby cities point 48.13743 11.57549 20000
...],"count":100,"cursor":110,"elapsed":"323.261µs"}
127.0.0.1:9851> nearby cities limit 50 point 48.13743 11.57549
...],"count":50,"cursor":0,"elapsed":"853.607µs"}`

KNN being slow here??!?!

**Comment by tidwall** [comment]
@tomquas I'm also finding that NEARBY KNN is slower than a NEARBY radius search. I think that this is the nature of the algorithm, but I'm going to try to do some further optimization.

What I found while implementing is that the KNN algorithm is much more complicated than a standard radius search because it needs to analyze the bounding rectangles based on proximity to the target point, and then pull leaf rectangles and then do further calculations. All the while sorting and kicking out rects that are out of range. It's constantly purging/sorting/adding to ensure that the resulting points are in order from nearest to farthest.

The radius search simply finds all rects that overlap the radius, and then do a haversine calc on each point. The order is undefined, and farthest point may be the first one returned. 

KNN is really nice when you don't know the radius, or you know that there may be a ton of objects nearby but you only need the closest. It can help you avoid having to fetch and sort tons of data just to find a couple nearby points. As mention by @joernroeder [here](https://github.com/tidwall/tile38/issues/130#issuecomment-273239390).

**Comment by tomquas** [comment]
@tidwall i'm not disappointed at all ;)

KNN ist still tremendously useful for my use case considering the big picture: instead of transferring lots of unused data between the database and application logic – usually over network – and burning cpu for filtering data, it's much better to process the data where it stays, namely in or very, very close to the database.

thanks again for implementing KNN in such a short time. i guess you just earned an A for responsiveness ;)

**Comment by tidwall** [comment]
@tomquas Thanks for the good grade!

**Comment by tidwall** [comment]
I'm closing this feature as completed. Feel free to reopen this issue if problems arise. Thanks!

**Comment by FX-HAO** [comment]
How is it going with nearby searches ordered by distance?

**Comment by tidwall** [comment]
@FX-HAO 

This feature was implenented a few months ago (04290ec). 

Just do a normal nearby search but exclude the distance and include a limit.

```
NEARBY fleet LIMIT 1 POINT 33.462 -112.268
```

This will return the single nearest object.

**Comment by FX-HAO** [comment]
@tidwall Yep, i love this feature, but do you have any plan for support both the radius and a limit? That's what i really needed.

**Comment by tidwall** [comment]
Yeah. It's something I plan on adding in the future.
