### ISSUE TITLE
Expose tile38 server API

### ISSUE THREAD

**Issue by mkorolyov** [tidwall/tile38#140]
Hi!

Thanks for such a great peace of work!

Are you planning to expose golang API so tile38 could be injected directly to existing server/app as a dependency?

There is a way to use tile38 in such way, e.g use redis client and point it to same host but msg serialization/desiarilization, etc are excess load.

BR's
Maxim

**Comment by m1ome** [comment]
@mkorolyov this is can be a problem, because Tile38 have a leader-follower replication and this ain't gonna work if you start in e.g. your application in one instance. [Replication](http://tile38.com/topics/replication/). If you need Geospatial indexes and KNN you can just use RTREE implementation, in one of my project I use it. 

On other hand you can use TCP for client connection and GRPC as a webhook proto and it will be pretty damn fast.

Also @tidwall can share if he plans to expose API of Tile38.

**Comment by tidwall** [comment]
I don't currently have plans to support Tile38 as an embeddable library. But that doesn't necessarily mean it's not possible today. Here's a discussion a while back #18 regarding using it as a library.

There are three interesting packages:
- [github.com/tidwall/tile38/geojson](https://godoc.org/github.com/tidwall/tile38/geojson)
- [github.com/tidwall/tile38/index](https://godoc.org/github.com/tidwall/tile38/index)
- [github.com/tidwall/tile38/controller/collection](https://godoc.org/github.com/tidwall/tile38/controller/collection)

The collection package is basically the core Tile38 minus networking, mutexes, disk writing, etc.

I recommend forking the project prior to using any of these libraries because the APIs will likely change over time.

**Comment by mkorolyov** [comment]
@tidwall thanks, it is a good start point, but i need hooks too. Seems like part of functionality is mixed in controller itself.

**Comment by tidwall** [comment]
@mkorolyov You're right. The hooks are wired into the base controller. It's much more complicated to expose webhooks and geofencing because they are a part of pipeline that includes the network, goroutines, and the disk.

**Comment by tidwall** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if needed. 

Thank you!
