### ISSUE TITLE
Dividing a region into geofences 

### ISSUE THREAD

**Issue by Salafi-Farooq** [tidwall/tile38#164]
Hey this is some tremendous software system for geospatial stuff.

I have a use-case wherein I need to divide a given geographical area, which can range from small region of few kilometers to a country, into geofences (static + roaming). How do you think I should proceed with this using tile38?

**Comment by amorskoy** [comment]
In fact I did probably the same. It was not perfect from the beginning, but finally we succeed with @tidwall 
See:
https://github.com/tidwall/tile38/issues/94
https://github.com/tidwall/tile38/issues/95
https://github.com/tidwall/tile38/issues/99
https://github.com/tidwall/tile38/issues/107
https://github.com/tidwall/tile38/issues/132
https://github.com/tidwall/tile38/issues/133

Finally, I was able to make good POC.

**Comment by tidwall** [comment]
Hi Salfi,

It shouldn't matter the size of the fence, just the complexity and the number of operations that it has to perform. A geofence is similar to a SET followed by a NEARBY, INTERSECTS, or WITHIN query on the defined fence area. For a complex geofence such as a country, it's ideal to use a GeoJSON object with a defined "bbox":

For example:

![image](https://cloud.githubusercontent.com/assets/1156077/24755725/1f23c866-1a90-11e7-8fe8-f81ebedea151.png)

Is better than:

![image](https://cloud.githubusercontent.com/assets/1156077/24755745/2e501bdc-1a90-11e7-9b2b-87b2b30374cd.png)

This is because the "bbox" won't need to be recalculated after each SET command.

If what you are interested crossing between geofences such as:

![image](https://cloud.githubusercontent.com/assets/1156077/24756973/98cfac3c-1a92-11e7-98d8-106061208943.png)

Then it could be worthwhile to reduce the fences down to a minimal threshold:

![image](https://cloud.githubusercontent.com/assets/1156077/24757023/c7004fa8-1a92-11e7-84b1-23e802ab938d.png)

put a boxes around those too:

![image](https://cloud.githubusercontent.com/assets/1156077/24757045/d6a4bc3c-1a92-11e7-8991-9568e42ffe2e.png)

and use the [DETECT enter](http://tile38.com/topics/geofencing/) option when defining both fences.

---

Here's some examples based on the images above:

```
SETHOOK enter-boliva http://127.0.0.1/fence INTERSECTS fleet FENCE DETECT enter OBJECT '{"type":"Polygon","bbox":[-63.325195,-21.983801,-57.612304,-18.458768],"coordinates":[[[-63.325195,-21.983801],[-62.819824,-21.983801],[-62.644042,-22.309425],[-62.292480,-21.063997],[-62.314453,-20.529933],[-61.918945,-20.076570],[-61.765136,-19.642587],[-60.380859,-19.373340],[-59.985351,-19.290405],[-59.084472,-19.269665],[-58.117675,-19.849393],[-58.117675,-20.220965],[-57.810058,-19.993998],[-58.029785,-19.663280],[-57.612304,-18.458768],[-63.325195,-18.458768],[-63.325195,-21.983801]]]}'
```
```
SETHOOK enter-paraguay http://127.0.0.1/fence INTERSECTS fleet FENCE DETECT enter OBJECT '{"type":"Polygon","bbox":[-62.644042,-22.309425,-57.857675,-19.269665],"coordinates":[[[-57.957675,-22.109425],[-62.644042,-22.309425],[-62.292480,-21.063997],[-62.314453,-20.529933],[-61.918945,-20.076570],[-61.765136,-19.642587],[-60.380859,-19.373340],[-59.985351,-19.290405],[-59.084472,-19.269665],[-58.117675,-19.849393],[-58.117675,-19.849393],[-58.117675,-20.220965],[-57.857675,-21.049393],[-57.957675,-22.109425]]]}'
```

These are just some ideas based on assumptions. I'm sure you application will differ quite a bit. Also roaming fences will increase the number of operations and notifications quite a bit. So you may want to do some basic testing on your side to see what throughput you get.

---

The original geojson which I created at http://geojson.io

### Bolivia
```json
{
  "type": "Polygon",
  "bbox": [-63.325195,-21.983801,-57.612304,-18.458768],
  "coordinates": [[
    [-63.325195,-21.983801],
    [-62.819824,-21.983801],
    [-62.644042,-22.309425],
    [-62.292480,-21.063997],
    [-62.314453,-20.529933],
    [-61.918945,-20.076570],
    [-61.765136,-19.642587],
    [-60.380859,-19.373340],
    [-59.985351,-19.290405],
    [-59.084472,-19.269665],
    [-58.117675,-19.849393],
    [-58.117675,-20.220965],
    [-57.810058,-19.993998],
    [-58.029785,-19.663280],
    [-57.612304,-18.458768],
    [-63.325195,-18.458768],
    [-63.325195,-21.983801]
  ]]
}
```
### Paraguay
```json
{
  "type": "Polygon",
  "bbox": [-62.644042,-22.309425,-57.857675,-19.269665],
  "coordinates": [[
    [-57.957675,-22.109425],
    [-62.644042,-22.309425],
    [-62.292480,-21.063997],
    [-62.314453,-20.529933],
    [-61.918945,-20.076570],
    [-61.765136,-19.642587],
    [-60.380859,-19.373340],
    [-59.985351,-19.290405],
    [-59.084472,-19.269665],
    [-58.117675,-19.849393],
    [-58.117675,-19.849393],
    [-58.117675,-20.220965],
    [-57.857675,-21.049393],
    [-57.957675,-22.109425]
  ]]
}

---

**Comment by tidwall** [comment]
@amorskoy I would love to hear more details about your POC and the application. If you have some time in the future. :)

**Comment by tidwall** [comment]
@Salafi-Farooq I'm closing this issue for now. Please feel free to reopen if you have further questions. Thanks!

**Comment by younisshah** [comment]
@tidwall How does go about geofencing a city?

**Comment by younisshah** [comment]
@tidwall Given a location specified as a lat/lon pair, how do I find which of many tens of thousands of geofences this location falls into using tile38?
