### ISSUE TITLE
Follower hearthbeat

### ISSUE THREAD

**Issue by ikks** [tidwall/tile38#172]
We have a setup of some followers of tile38, we would want to know if there is a way to know if a follower is synced with the main tile38-server.  Our purpose is putting the master with the writes and the followers to distribute the load of queries.

We simulated a network outage between the follower and the master, during three minutes, then restored the network and we saw that the follower ends up out of sync.

Do you have something in the plan to query the follower or the main server to know the status of the sync?  Or even better to have a more resilent setup for the followers when there are network problems?

**Comment by tidwall** [comment]
When a server begins following, either from the `FOLLOW` command or from a server restart, it may take a moment to completely get in sync with the leader. You can send a `SERVER` command and check if `caught_up` equals true. 

Once the follower is caught up there is no longer a way for that follower to know if behind the leader. This is because it's the responsibility of the leader to push all writes to it's followers and the follower doesn't know it's last received write command is the latest. 


In your case did the follower eventually sync up? This is the first time that I've heard of where a leader and follower do not resync after a restore from a network connection. I would certainly like to reproduce this issue on my side. 

> Do you have something in the plan to query the follower or the main server to know the status of the sync? Or even better to have a more resilent setup for the followers when there are network problems?

There's no plans at the moment, but something could be added such as comparing the AOF modified timestamp of a follower to leader. Or a bidirectional pings where a follower or leader will know the time it they handshaked. Then perhaps followers that are too far behind can be handled by client differently.

**Comment by ikks** [comment]
We made some tests unplugging cables to simulate the network failure, we used the same IP address on the follower and in three times the follower didn't sync, it was a 3 minutes of no connection, then plugged again, we waited like 10 minutes, but the follower didn't catch up.

Those were the conditions we used.

**Comment by tidwall** [comment]
OK, thanks for the extra information. I'm wonder it's related to #145. I'll investigate further on my side and keep you posted.

**Comment by ikks** [comment]
We have been using in production tile38 and with a reliable connection and haven't had any problems, thank you.
