### ISSUE TITLE
Docs: "LIMIT" is ignored for COUNT?

### ISSUE THREAD

**Issue by thanatos** [tidwall/tile38#209]
The documentation for [output formats for `NEARBY`, `WITHIN`, and `INTERSECTS`](http://tile38.com/commands/intersects/#output-formats) says,

> **COUNT** - Total object count for the search. *LIMIT and CURSOR options are ignored*

Is `LIMIT` actually ignored, or is the documentation wrong here?

Quick tests on my data seem to indicate that `LIMIT` *isn't* ignored, which is actually the behavior I expect here. If I query a `TILE` that contains 50000+ points with a `WITHIN` and `COUNT`,

```
127.0.0.1:9851> WITHIN addr COUNT TILE 1309 3166 13
{"ok":true,"count":100,"cursor":0,"elapsed":"141.645µs"}
127.0.0.1:9851> WITHIN addr LIMIT 200 COUNT TILE 1309 3166 13
{"ok":true,"count":200,"cursor":0,"elapsed":"185.96µs"}
127.0.0.1:9851> WITHIN addr LIMIT 10000 COUNT TILE 1309 3166 13
{"ok":true,"count":10000,"cursor":0,"elapsed":"7.097298ms"}
127.0.0.1:9851> WITHIN addr LIMIT 50000 COUNT TILE 1309 3166 13
{"ok":true,"count":50000,"cursor":0,"elapsed":"34.34955ms"}
127.0.0.1:9851> WITHIN addr LIMIT 5000000 COUNT TILE 1309 3166 13
{"ok":true,"count":71916,"cursor":0,"elapsed":"50.187649ms"}
```

And this should make sense; e.g., in SQL databases, `LIMIT` is optionally used to constrain the number of rows the DB might need to count.

(My use case is that sometimes, an area has "too many" points, and returning a count to the client is simpler, quicker, and better UI for the user that drawing a bajillion points on the screen.)

**Comment by tidwall** [comment]
It appears that the documentation is incorrect. 

The way it should work is that when COUNT is provided the query simply counts over the results. 

When LIMIT or CURSOR are provided then COUNT returns the number of results that would otherwise be sent as objects. 

When LIMIT is **not** specified then COUNT totals up all items starting from provided CURSOR position (or zero if a cursor is omitted). 

For a simple query like `SCAN addr COUNT`, the total number of items in the collection are sent.

https://github.com/tile38/tile38.github.io/issues/7

**Comment by s32x** [comment]
https://github.com/tile38/tile38.github.io/pull/24 Resolves this
