### ISSUE TITLE
Add v prefix to release versions

### ISSUE THREAD

**Issue by ebati** [tidwall/tile38#347]
go 1.11 added [modules support](https://github.com/golang/go/wiki/Modules) and it only accepts semver tags with `v` prefix ([related semver parser code](https://github.com/golang/go/blob/24e5fae92e2c971fa30ac170b7656ff14f3cfde5/src/cmd/go/internal/semver/semver.go#L19)) . Is it possible to prefix releases with `v`.

**Comment by tidwall** [comment]
This may be possible. We'll look into it. Are you importing stuff from the `pkg` directory?

**Comment by ebati** [comment]
Yes, i am using pkg/geojson and the returned object to check for some points if they are in poly.

**Comment by s32x** [comment]
@ebati Since Tile38 is now a completely isolated service and the majority of its functionality is internal, we'll keep with the non-v convention for now. However you should be able to import GeoJSON since it has been split out into its own repository which supports go modules tagging. You can import it here - https://github.com/tidwall/geojson. Hopefully, this helps! If not feel free to re-open this issue.

**Comment by tidwall** [comment]
I want to point out that the new https://github.com/tidwall/geojson project has a complete rewritten codebase from the previous github.com/tidwall/tile38/pkg/geojson.

For the newest code use the `v1.0.0` tag and for the old geojson code use `v0.9.0`.

**Comment by ebati** [comment]
Thanks for helpful response :relaxed:
