### ISSUE TITLE
Timestamp in tile38

### ISSUE THREAD

**Issue by useris20x** [tidwall/tile38#387]
Hi,

I'm starting using tile38 for my my project.
Do we have possabilities to add timestamp?
For example: nearby fleet fence point 33.462 -112.268 6000 AT 2018-11-18 08:00 and filter by datetime object?

**Comment by tidwall** [comment]
Sort of. There's no DateTime type specifically, but all objects can have fields which are stored as double precision floating points.

You can achieve a similar behavior by storing the timestamp as a unix epoch.

For example:

```
SET fleet truck1 FIELD ts 1542553200 POINT 33.462 -112.268
```

The `1542553200` is `2018-11-18 08:00` (https://www.epochconverter.com/)

Now you can do your NEARBY fence:

```
NEARBY fleet FENCE WHERE ts 1542524400 1542610800 POINT 33.462 -112.268 6000
```

This will filter the NEARBY on all objects that are between `2018-11-18 00:00` and `2018-11-19 00:00`

**Comment by tobilg** [comment]
That‘s a great solution! Is there a way to store the Position history of objects as well?

**Comment by s32x** [comment]
`Because Tile38 is an in-memory database you'll want to watch out for storing too much history`

This is an important thing to keep in mind. Since Tile38 is very dependant on RAM, I'd recommend you store historical data in a place that is less limited (on disk). You could very easily run out of memory by storing large amounts of historical data in Tile38.
