### ISSUE TITLE
Expiration Hook

### ISSUE THREAD

**Issue by 1995parham** [tidwall/tile38#417]
Is there any to have a hook for ID expiration? I mean can we run a function when ID got expired?

**Comment by tidwall** [comment]
It's possible. Here's an example:

```
SETHOOK hook1 ... INTERSECTS fleet FENCE DETECT enter COMMANDS del BOUNDS -90 -180 90 180
```

This monitors the entire world, but only sends a notification when an ID has been deleted or expires. 

```
SET fleet truck1 EX 1 POINT 33 -115
```

will output the following notification.

```json
{"command":"del","hook":"hook1","id":"truck1","time":"2019-02-23T08:49:29.303674-07:00"}
```

**Comment by 1995parham** [comment]
@tidwall thanks for your guidance. I will try it.

**Comment by iwpnd** [comment]
Nope @Kilowhisky

**Comment by Kilowhisky** [comment]
Fun stuff, 

I ended up working around this by setting all my string objects which happen to be JSON with a random point on the planet. 
I need to use a random point due to indexing getting overloaded when too many points are at the same location. 

Since STRING support is so lacking my suggestion is to just wrap every STRING object in a pseudo GeoJson object with a random point on the planet and go from there.

**Comment by iwpnd** [comment]
Sounds niche but if it works for you, all the better 😅
