### ISSUE TITLE
Tile38 NEARBY command Distance issue

### ISSUE THREAD

**Issue by TrivikrAm-Pamarthi** [tidwall/tile38#422]
Hi... 
I had created a fleet with below 

SET fleet manyata POINT 13.052758 77.618843
SET fleet silkboard POINT 12.885970 77.656180
SET fleet tinfactory POINT 12.529260 76.904930
SET fleet hyderabad POINT 17.385044 78.486671

And while i running the below query 

NEARBY fleet DISTANCE match hyd* POINT  13.0257553 77.6672509 9000000

i'm getting 

{"ok":true,"objects":[],"count":0,"cursor":0,"elapsed":"0s"}

And also while doing with the below query

NEARBY fleet DISTANCE match hyd* POINT  13.0257553 77.6672509 900000

i'm getting 

{"ok":true,"objects":[{"id":"hyderabad","object":{"type":"Point","coordinates":[
78.486671,17.385044]},"distance":492636.04872003023}],"count":1,"cursor":0,"elap
sed":"0s"}

please check this..
Thank you

**Comment by tidwall** [comment]
Hi, 
9,000,000 is a big number. Much larger than the radius of the earth. I'm thinking that that may be where the issue lies. I agree that this should be fixed and I appreciate you reporting the issue. 

In the meantime, if your goal is to return the distance to every object in a collection from a specified point, then I suggest foregoing the radius altogether.

```
NEARBY fleet DISTANCE match hyd* POINT 13.0257553 77.6672509
```

This will returns all the points.

**Comment by tidwall** [comment]
Reopening the issue until #466 is merged.
