### ISSUE TITLE
AOFSHRINK crashes when using replication on Windows.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [tidwall/tile38#449]
Happening on tile38-1.17.0-windows-amd64 when replicating with 1 server following, different data directories.

Followed guide here: https://tile38.com/topics/replication/

Possibly related to #211

```shrink backup fatal operation: rename data1/appendonly.aof data1/appendonly.aof-bak: The process cannot access the file because it is being used by another process.```

Crash reproducible on either server, if no replicating servers are connected then it works.

I don't think that this is by design?

https://tile38.com/commands/aofshrink/

**Comment by tidwall** [comment]
That's definitely not by design. 
Yes, I'm also thinking that's it's related to #221
Do you happen to have the crash log?

**Comment by mzbrau** [comment]
Hi, thanks for the great product!

I am also having this problem running the latest version (1.24.2) on Windows 10. 

If I have 2 instances of tile 38 running, one on port 9851 and the other 9852, I then do:
`tile38-cli.exe -p 9852 FOLLOW localhost 9851`
`tile38-cli.exe -p 9851 AOFSHRINK`

The second command will crash the 9851 instance with the following error:
`shrink backup fatal operation: rename data/appendonly.aof data/appendonly.aof-bak: The process cannot access the file because it is being used by another process.`

It appears that the 9851 process has 2 handles on the file, presumably one for writing the commands and the other for serving the follower. My guess is that when I perform the `AOFSHRINK` command at least one of these handles has  lock on the file and the thread trying to perform the shrink throws an exception.
![image](https://user-images.githubusercontent.com/49205235/121649105-8202e680-ca98-11eb-9c86-be6f6133cb2c.png)

I am working around it at the moment by swapping the leader and only performing the shrink operation on the followers. However, I have seen a rare instance when the server still seems to have the lock on the file when it stops being the leader and begins to follow another server instance and then it crashes too on a shrink request. I haven't found any reliable reproduction steps just yet for that issue.

Based on this comment it seems like once the error is raised, exiting the process is by design:
https://github.com/tidwall/tile38/blob/master/internal/server/aofshrink.go#L267

I was wondering if it would be possible to check if the file is locked and just fail the shrink operation rather than terminating the whole application?

I see you requested a crash log above, I'm happy to get that if you are unable to reproduce the problem if you can point me to the steps. Running the server with -vv just produces the same output as listed above.

Thanks, Michael

**Comment by tidwall** [comment]
Hi, thanks for the detailed report.

The error is puzzling. I know that Windows does not like it when opened files are renamed or overwritten, but both the "data/appendonly.aof" and "data/appendonly.aof-bak" are closed [immediately prior](https://github.com/tidwall/tile38/blob/master/internal/server/aofshrink.go#L269-L274) to the [Rename](https://github.com/tidwall/tile38/blob/master/internal/server/aofshrink.go#L275) call.

So that has me thinking that the "data/appendonly.aof" file is opened elsewhere. Either in a background routine or by a process external to Tile38.

I'll have to poke around the code to learn more.

**Comment by tidwall** [comment]
You are right about the multiple file handles and I addressed the issue in #611
