### ISSUE TITLE
Question: Use Tile38 to de-dupe data?

### ISSUE THREAD

**Issue by owaaa** [tidwall/tile38#63]
I have some data i want to de-duplicate geo-spatially.  I was trying to see if there is a way to see what data is near other data within a key. For example, people near people or place near place. I looked at the ROAM option within geofence but I don't think it works for me as the data is static . I could iterate through but wanted to see if there is a better way. Any ideas?

**Comment by tidwall** [comment]
Hi Andrew,

That's an interesting problem. I agree that iterating through all of the data would not be the best way. There isn't any commands in Tile38 that are specifically for the purpose of de-duplication.

The ROAM option won't work because it's for actively changing data.

The best of what I can think of is the SPARSE option which returns 4,8,16,32,... objects from a query.

```
NEARBY people SPARSE 1 POINT 33.11 -115.23 10000
```

This will return at the most 4 objects, even though there might be thousands of objects that might have been returned otherwise.

==

Maybe another option is to break the area that you are de-duplicating into small bounding rects. Then iterate though the rects by doing a WITHIN operation on each. Finally DEL the ids of the items that you do not want.  

==

Lastly I could always implement new features. Something that facilitates nearby-neighbors or such.

**Comment by owaaa** [comment]
Yea, I don't think there should be a specific feature for de-duplicating, I was just wondering if there was a clever way in Tile38 to compare geometries in a key vs other geometries in the same key.

**Comment by tidwall** [comment]
I'm closing this issue for now. If you have any further ideas around this topic, please feel free to reopen.

On a side note, we recently added [KNN support](https://github.com/tidwall/tile38/commit/04290ec535aed0e6dbeb48ef8cbadaaf92591a8e), which can help minimize the number of results in some cases.
