### ISSUE TITLE
Auth not working when using Lettuce as client

### ISSUE THREAD

**Issue by rave-eserating** [tidwall/tile38#636]
**Describe the bug**
When I attempt to create a Lettuce Redis connection to Tile38 that has a password set, it always responds with an authentication required error.

**To Reproduce**
Set the Tile38 config to require a password as follows:
```# Test config
{
    "requirepass": "test1234"
}
```
Using Lettuce version: 6.1.5.RELEASE
Use lettuce to try to create a connection to Tile38, passing in the password in the config:

Imports used:
```
import io.lettuce.core.RedisClient;
import io.lettuce.core.RedisURI;
import io.lettuce.core.api.StatefulRedisConnection;
```

Run the following code to simply create a connection, it will fail on connection creation:
```
RedisURI uri = RedisURI.Builder.redis("localhost", 56499)
                .withPassword("test1234").build();
        RedisClient redisClient = RedisClient.create(uri);
        StatefulRedisConnection<String, String> redisConnection = redisClient.connect();
```

**Expected behavior**
I would expect that setting the password correctly in the RedisClient would work and Tile38 would accept the auth.

**Logs**
```Unable to connect to localhost:56499
io.lettuce.core.RedisConnectionException: Unable to connect to localhost:56499
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
     ...
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR authentication required```

**Comment by tidwall** [comment]
Sorry for the delay.  This took me a little time to figure out.

The short answer is that you need to set the protocol version to RESP2, like this:

```
RedisURI uri = RedisURI.Builder.redis("localhost", 56499)
        .withPassword("test1234").build();
RedisClient redisClient = RedisClient.create(uri);
redisClient.setOptions(ClientOptions.builder().protocolVersion(ProtocolVersion.RESP2).build());
StatefulRedisConnection<String, String> redisConnection = redisClient.connect();
```

The long answer is that Redis has recently updated their protocol to RESP3, which supports a new HELLO handshake that includes a protocol version and auth password in a single command. This is an alternative to old AUTH command from RESP2.

The lettuce client attempts to do an auto detection when a connection is made. First trying the HELLO command, then if it received an ERR response, it fallback to sending an AUTH command.

For a Redis server this works fine. But, for Tile38 this fails because Tile38 and Redis differ slightly in the way authentication is handled.

I recommend the workaround above, but I also added a little change to Tile38 so that this won't be a problem with lettuce in the future.

**Comment by rave-eserating** [comment]
Hi @tidwall, thank you for the very fast turn around on this.

**Comment by tidwall** [comment]
You're welcome and thanks for reporting.

**Comment by rave-eserating** [comment]
Using ProtocolVersion.RESP2 solves the issue, closing the ticket.
